import type { Metadata } from "next";
import Navigation from '../components/navigation';
import { Inter } from "next/font/google";
import "./globals.css";
import { SanityDocument } from "next-sanity";
import { sanityFetch } from "@/sanity/client";

const inter = Inter({ subsets: ["latin"] });
const NAV_MENU_QUERY = `*[_type == "navigationList"] {navArray[]->}`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navMenu = await sanityFetch<SanityDocument[]>({query: NAV_MENU_QUERY});

  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <Navigation navArray={navMenu[0].navArray}/>
        <main>{children}</main>
        <footer>copyright</footer>
      </body>
    </html>
  );
}
